function generate_radial_machine_fixtures (rnfoundryRoot, outputDirectory)
%GENERATE_RADIAL_MACHINE_FIXTURES Regenerate the checked-in FEM fixtures.
%
% This maintenance helper requires RNFoundry. The generated fixtures do not,
% so the actual xfemm regression tests remain self-contained and CI-friendly.

    if nargin < 2 || isempty (outputDirectory)
        outputDirectory = fullfile (fileparts (mfilename ('fullpath')), 'data');
    end
    if exist (outputDirectory, 'dir') ~= 7
        mkdir (outputDirectory);
    end

    % A short redraw run performs the same design completion and simulation
    % option setup as the tutorial. The returned design/options are then used
    % only to draw deterministic input fixtures; its solutions are discarded.
    [~, design, simoptions] = radial_machine_static_case (rnfoundryRoot, ...
        'SolveMethod', 'xfemm_legacy', ...
        'RotationMethod', 'MagnetRedraw', ...
        'NPositions', 2);

    positions = linspace (0, 1, 10);
    nPolePairs = max (1, ceil (design.pb / 2));
    for ind = 1:numel (positions)
        problem = draw_problem (design, simoptions, nPolePairs, ...
                                design.thetap * positions(ind), ...
                                'MagnetRotation');
        filename = fullfile (outputDirectory, ...
                             sprintf ('radial_machine_redraw_%02d.fem', ind));
        writefemmfile (filename, problem);
    end

    problem = draw_problem (design, simoptions, nPolePairs, 0, 'SlidingMesh');
    writefemmfile (fullfile (outputDirectory, ...
                            'radial_machine_sliding.fem'), problem);

    positionFile = fullfile (outputDirectory, 'positions.txt');
    fid = fopen (positionFile, 'w');
    assert (fid >= 0, 'Could not open %s for writing.', positionFile);
    cleanup = onCleanup (@() fclose (fid));
    fprintf (fid, '%.17g\n', positions);
end


function problem = draw_problem (design, simoptions, nPolePairs, theta, drawingType)
    [problem, ~, ~] = slottedfemmprob_radial (design, ...
        'NPolePairs', nPolePairs, ...
        'NWindingLayers', design.CoilLayers, ...
        'SplitSlot', (design.CoilLayers == 2) && (design.yd == 1), ...
        'Position', theta, ...
        'MagnetRegionMeshSize', simoptions.MagFEASim.MagnetRegionMeshSize, ...
        'BackIronRegionMeshSize', simoptions.MagFEASim.BackIronRegionMeshSize, ...
        'StatorOuterRegionsMeshSize', simoptions.MagFEASim.OuterRegionsMeshSize, ...
        'RotorOuterRegionsMeshSize', simoptions.MagFEASim.OuterRegionsMeshSize, ...
        'AirGapMeshSize', simoptions.MagFEASim.AirGapMeshSize, ...
        'ShoeGapRegionMeshSize', simoptions.MagFEASim.ShoeGapRegionMeshSize, ...
        'YokeRegionMeshSize', simoptions.MagFEASim.YokeRegionMeshSize, ...
        'CoilRegionMeshSize', simoptions.MagFEASim.CoilRegionMeshSize, ...
        'CoilCurrent', zeros (design.Phases, 1), ...
        'DrawingType', drawingType);
end
