if(NOT EXISTS "${SOLUTION_FILE}")
    message(FATAL_ERROR "Solution file was not created: ${SOLUTION_FILE}")
endif()
file(SIZE "${SOLUTION_FILE}" _solution_size)
if(_solution_size LESS 100)
    message(FATAL_ERROR "Solution file is unexpectedly small: ${_solution_size} bytes")
endif()
file(STRINGS "${SOLUTION_FILE}" _solution_marker REGEX "^\[Solution\]$")
if(NOT _solution_marker)
    message(FATAL_ERROR "Solution file has no [Solution] section")
endif()
